trigger:

 branches:
   include:
     - main
pool: mypool1

steps:

- task: TerraformInstaller@1
  displayName: Terraform Install
  inputs:
    terraformVersion: 'latest'


- task: TerraformTask@5
  displayName: Terraform init
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(Build.SourcesDirectory)/'
    backendServiceArm: 'workload idy fedration-SCN'
    backendAzureRmResourceGroupName: 'myResourceGroup'
    backendAzureRmStorageAccountName: 'mystorage12340'
    backendAzureRmContainerName: 'radha'
    backendAzureRmKey: 'radha.tfstate'

- task: TerraformTask@5
  displayName: Terraform validate
  inputs:
    provider: 'azurerm'
    command: 'validate'
    workingDirectory: '$(Build.SourcesDirectory)/'

- task: TerraformTask@5
  displayName: Terraform Plan
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '$(Build.SourcesDirectory)/'
    environmentServiceNameAzureRM: 'workload idy fedration-SCN'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'apply'
    commandOptions: '--auto-approve'
    environmentServiceNameAzureRM: 'workload idy fedration-SCN'

