trigger:

 branches:
   include:
     - main
pool: mypool1

variables: 
  config_path: '$(Build.SourcesDirectory)/'
  backend_svn: 'workload idy fedration-SCN'

steps:
- task: TerraformInstaller@1
  displayName: Terraform Install
  inputs:
    terraformVersion: 'latest'


- task: TerraformTask@5
  displayName: Terraform init
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: $(config_path)
    backendServiceArm: $(backend_svn)
    backendAzureRmResourceGroupName: 'myResourceGroup'
    backendAzureRmStorageAccountName: 'mystorage12340'
    backendAzureRmContainerName: 'radha'
    backendAzureRmKey: 'radha.tfstate'

- task: TerraformTask@5
  displayName: Terraform validate
  inputs:
    provider: 'azurerm'
    command: 'validate'
    workingDirectory: $(config_path)

- task: TerraformTask@5
  displayName: Terraform Plan
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: $(config_path)
    environmentServiceNameAzureRM: $(backend_svn)

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'apply'
    commandOptions: '--auto-approve'
    environmentServiceNameAzureRM: $(backend_svn)

